"use strict";

/* ===================================================== deploy.js
   Service worker source, web-app manifest, icon, README, and the
   "Export deployment package" logic that bundles the split
   source files (not the live DOM) into an installable PWA zip.   */

/* --------------------------------------------------- deployment packaging */
/* The application now ships as several source files rather than one HTML
   file. Anything the shell needs to boot while offline — the markup, the
   stylesheet and every script — has to be named here so the install step
   actually caches it; a stale list would silently break offline reloads. */
const SOURCE_FILES = ["index.html", "styles.css", "core.js", "shared/schema.js", "rules.js",
  "engine.js", "afrd.js", "import.js", "views.js", "events.js", "pdf.js", "letters.js", "deploy.js"];

const SW_SOURCE = '/* RBCCI LPMRS service worker, generated by the application.\n'
+ '   Deploy beside index.html and serve both over https or http://localhost. */\n'
+ 'const CACHE = "rbcci-lpmrs-v' + APP.version + '";\n'
+ 'const SHELL = ["./", ' + SOURCE_FILES.map(f => '"./' + f + '"').join(", ") + ', "./manifest.webmanifest", "./icon.svg"];\n'
+ 'self.addEventListener("install", e => {\n'
+ '  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting()));\n'
+ '});\n'
+ 'self.addEventListener("activate", e => {\n'
+ '  e.waitUntil(caches.keys()\n'
+ '    .then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k))))\n'
+ '    .then(() => self.clients.claim()));\n'
+ '});\n'
+ 'self.addEventListener("fetch", e => {\n'
+ '  const url = new URL(e.request.url);\n'
+ '  if (url.origin !== self.location.origin) return;   // same-origin only\n'
+ '  if (e.request.method !== "GET") return;\n'
+ '  e.respondWith(caches.match(e.request).then(hit => hit || fetch(e.request).then(res => {\n'
+ '    const copy = res.clone();\n'
+ '    caches.open(CACHE).then(c => c.put(e.request, copy)).catch(() => {});\n'
+ '    return res;\n'
+ '  }).catch(() => caches.match("./index.html"))));\n'
+ '});\n';

const MANIFEST_SOURCE = JSON.stringify({
  name: "RBCCI Loan Portfolio Management and Reporting System",
  short_name: "RBCCI LPMRS",
  description: "Offline-first loan portfolio management and reporting for Rural Bank of Calbayog City, Inc.",
  start_url: "./index.html", scope: "./", display: "standalone",
  background_color: "#eef3f0", theme_color: "#0f3d2e",
  icons: [{ src: "icon.svg", sizes: "any", type: "image/svg+xml", purpose: "any maskable" }]
}, null, 2);

const ICON_SOURCE = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><rect width="512" height="512" rx="96" fill="#0f3d2e"/><rect x="112" y="128" width="288" height="256" rx="20" fill="none" stroke="#b8873a" stroke-width="16"/><g fill="#b8873a"><rect x="160" y="288" width="40" height="56" rx="6"/><rect x="216" y="248" width="40" height="96" rx="6"/><rect x="272" y="208" width="40" height="136" rx="6"/><rect x="328" y="176" width="24" height="168" rx="6"/></g></svg>';

const DEPLOY_README = 'RBCCI LPMRS - deployment package\n'
+ '================================\n\n'
+ 'Files in this folder\n'
+ '  index.html              markup shell\n'
+ '  styles.css               all styling\n'
+ '  core.js                  helpers, ZIP/XLSX/CSV codecs, OPFS vault, encryption\n'
+ '  shared/schema.js         column field list and header-mapping, shared with the\n'
+ '                            backend pre-check at api/verify-import.js\n'
+ '  rules.js                 default rule pack, app state, login/session/audit\n'
+ '  engine.js                classification engine, movement, amortisation\n'
+ '  afrd.js                  AFRD investments register and compliance computation\n'
+ '  import.js                column mapping, import, export, backup restore\n'
+ '  views.js                 every screen, and the account drawer\n'
+ '  events.js                render/wire/act and boot\n'
+ '  pdf.js                   the formatted PDF report writer\n'
+ '  letters.js               collection correspondence templates and writers\n'
+ '  deploy.js                this packaging logic and the service worker source\n'
+ '  rbcci-lpm-sw.js          service worker, provides the offline shell\n'
+ '  manifest.webmanifest    installability metadata\n'
+ '  icon.svg                application icon\n\n'
+ 'Why this package exists\n'
+ '  A service worker must be loaded from a same-origin http: or https: URL and\n'
+ '  served with a JavaScript MIME type, so none of this can be installed by\n'
+ '  double-clicking a file. Placing every file above in one folder and serving\n'
+ '  them together satisfies the standard.\n\n'
+ 'Deploying on a bank workstation\n'
+ '  1. Copy every file above into one folder on the internal web server, or\n'
+ '     serve the folder locally, for example:   py -m http.server 8080\n'
+ '  2. Open http://localhost:8080/index.html or the internal https URL.\n'
+ '  3. The browser offers to install the application. After the first load it\n'
+ '     runs with the network disconnected.\n'
+ '  4. Confirm in the browser application panel that the service worker is\n'
+ '     active and the manifest is detected.\n\n'
+ 'Notes\n'
+ '  - Loan data is stored in the Origin Private File System of the browser\n'
+ '    profile, not on the server. The server only delivers the application shell.\n'
+ '  - Serve over https, or over localhost, or the service worker will not register.\n'
+ '  - Do not place loan files in the web folder.\n\n'
+ 'Generated by RBCCI LPMRS ' + APP.version + '.\n';

async function exportDeployment() {
  /* The application is split across several source files that sit beside
     index.html on the server. This re-reads each one of those files (not
     the live, rendered DOM) so the package matches what is actually on
     disk, then adds the generated service worker, manifest, icon and a
     README. fetch() cannot read sibling files under file:, so packaging
     only works once the application is already being served over http or
     https — which is also a requirement for the service worker itself. */
  if (location.protocol !== "http:" && location.protocol !== "https:") {
    toast("This only works when the application is opened from a web address rather than from a file on disk. Ask whoever installed it to place the files on the bank's internal server, then try again from there.", "err");
    return;
  }
  try {
    toast("Packaging deployment files...");
    const files = [];
    for (const name of SOURCE_FILES) {
      const res = await fetch(name, { cache: "no-store" });
      if (!res.ok) throw new Error("could not read " + name + " (HTTP " + res.status + ")");
      files.push({ name, data: await res.text() });
    }
    files.push({ name: "rbcci-lpm-sw.js", data: SW_SOURCE });
    files.push({ name: "manifest.webmanifest", data: MANIFEST_SOURCE });
    files.push({ name: "icon.svg", data: ICON_SOURCE });
    files.push({ name: "README.txt", data: DEPLOY_README });
    const blob = await ZipWrite.build(files);
    download("RBCCI_LPMRS_deployment_" + today().replace(/-/g, "") + ".zip", blob);
    audit("Exported deployment package", SOURCE_FILES.length + " source files, service worker, manifest, icon");
    toast("Deployment package exported. Unzip the files into one folder and serve them together.");
  } catch (e) { toast("Packaging failed: " + e.message + ". Each source file must be reachable at its own URL next to index.html.", "err"); }
}

(function registerSw() {
  if (!("serviceWorker" in navigator)) return;
  if (location.protocol !== "http:" && location.protocol !== "https:") return;
  navigator.serviceWorker.register("rbcci-lpm-sw.js")
    .then(function () { audit("Service worker registered", "offline shell active"); })
    .catch(function () { /* not deployed yet; the application still runs */ });
})();
